# Basic settings
basics:
  site_title: Bali Pledge
  description: To be in harmony with the local community, to protect Bali's natural resources, to respect the cultural and spiritual essence of Bali.
  site_base_url: 'https://mysite.com'
  site_logo_image: '/assets/bali-pledge-logo-02.svg'
  site_thumb_image: 'assets/bali-pledge-logo-03.png'
  contact_email: 'balipledge@gmail.com'
  phone_number: ""
  address: 'Ubud, Bali, Indonesia'
social:
  facebook_url: 'https://facebook.com'
  instagram_url: 'https://instagram.com'
  instagram_handle: '@yourhandle'
  twitter_url: 'https://twitter.com'
  twitter_handle: '@yourhandle'
  youtube_url: 'https://youtube.com'
  github_url: 'https://github.com'
  linkedin_url: 'https://linkedin.com'
  snapchat_url: 'https://snapchat.com'
  stackoverflow_url: 'https://stackoverflow.com'
navigation:
  menu_1_url: '/#illustrated-quote-1'
  menu_2_url: '/#pledge'
  menu_3_url: '/#custom-message'
  menu_4_url: '/#footer'
  menu_5_url:
  menu_6_url:
# Brand identity

# Global colors. Put HEX values between quotes otherwise it will act as a comment in YAML
colors:
  primary_color: "#333333"
  secondary_color: "#383231"
  primary_shade_color: "#aeaeae"
  secondary_shade_color: "#999999"
  accent_color: "#e9a547"

# Typography (can be customized to accomodate more styles like standard font sizes and line height)
fonts:
  fonts_code_block:  '<link href="https://fonts.googleapis.com/css?family=Eczar:600,700|Noto+Serif+KR:200,400,500&display=swap&subset=devanagari" rel="stylesheet">
' # Place between single quotes
  body_font_family: "'Noto Serif KR', serif;"
  design_font_family: "'Eczar', serif;"

seo:
  fb_app_id:
  keywords: [bali pledge, ubud, bali sustainable]
  description: The Bali Pledge is a sustainability initiative aimed at raising awareness of preservation of the culture, land and customs of Bali to visitors and all residents.

# Analytics & embeds
configuration:
  google_tag_manager_code_block:
  google_analytics_code_block:
  form_submission_handler_code_block:
  flexbox_framework_code_block: '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.1/gridlex.min.css">'
  fontawesome_code_block:
